In [39]:
import os
import pandas as pd
from collections import Counter
import string

In [40]:
chord_types = []
for file in os.listdir('../corpus/chords_sequences'):
    
    song = file.split('.csv')[0]
    df = pd.read_csv('../corpus/chords_sequences/'+file)

    for i in df.index:
        chord = df.iloc[i][song]
        chord = chord.split('/')[0]
        
        note = df.iloc[i]['chord_note']
        
        chord_type = chord.replace(note, '')
        chord_types.append(chord_type)

In [46]:
df_types = pd.DataFrame(Counter(chord_types).most_common(45))
df_types.rename(columns={0:'chord_type', 1:'freq'}, inplace=True)
df_types

           chord_type  freq
0                   7  4449
1                min7  3094
2                maj7  1136
3                      1044
4                   9   592
5                  13   414
6               7(#9)   267
7                 min   209
8               min11   110
9                min9    99
10           min7(b5)    86
11               dim7    76
12                maj    67
13                dim    60
14                  6    45
15               maj9    32
16             7(#11)    30
17               min6    25
18                sus    23
19          min(maj7)    23
20           7sus(07)    22
21              7(b9)    18
22              7(b5)    16
23              min13    15
24                mi7    14
25              maj13    13
26              7(#5)    10
27         maj13(#11)    10
28               maj6    10
29          min7(0##)    10
30                ma7     9
31  minor-seventh(b5)     8
32                 m7     8
33                  5     6
34             9(#11)     5
35  augmented-seventh     4
36           min7(09)     4
37       dominant(#9)     3
38          maj7(#11)     3
39    major-minor(09)     3
40             13(#9)     2
41          augmented     2
42          major(09)     1
43             9(0#3)     1
44        maj7sus(b5)     1