In [1]:
import pandas as pd

In [8]:
test = pd.read_csv('../corpus/chords_sequences/MoonRiver.csv')
test

    Measure   MoonRiver   Time
0         1       Cmaj7   0.00
1         2       Amin7   1.50
2         3     F7(#11)   3.00
3         4       Cmaj7   4.50
4         5          F7   6.00
5         6       Cmaj7   7.50
6         7   Bmin7(b5)   9.00
7         8          E7  10.50
8         9       Amin7  12.00
9        10        C7/G  13.50
10       11       Fmaj7  15.00
11       12         Bb7  16.50
12       13       Amin7  18.00
13       13     Amin7/G  18.75
14       14      F#min7  19.50
15       14          B7  20.25
16       15       Emin7  21.00
17       15          A7  21.75
18       16        Dmin  22.50
19       16          G7  23.25
20       17       Amin7  24.00
21       18     Amin7/G  25.50
22       19  F#min7(b5)  27.00
23       20          F7  28.50
24       21       Cmaj7  30.00
25       22       Fmaj7  31.50
26       23       Cmaj7  33.00
27       24        Fmaj  34.50
28       25       Emin7  36.00
29       26       Amin7  37.50
30       27       Dmin7  39.00
31       28          G7  40.50
32       29       Cmaj7  42.00
33       30       Dmin7  43.50
34       30          G7  44.25

In [10]:
for i in test.index:
    chord = test.iloc[i]['MoonRiver']
    chord = chord.split('/')[0]
    print(chord.split('/')[0])

Cmaj7
Amin7
F7(#11)
Cmaj7
F7
Cmaj7
Bmin7(b5)
E7
Amin7
C7
Fmaj7
Bb7
Amin7
Amin7
F#min7
B7
Emin7
A7
Dmin
G7
Amin7
Amin7
F#min7(b5)
F7
Cmaj7
Fmaj7
Cmaj7
Fmaj
Emin7
Amin7
Dmin7
G7
Cmaj7
Dmin7
G7